---
version: 2.1
workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              device: ["motorola_q14", "motorola_mh7020", "motorola_r14"]
          #context: deployable-service

jobs:
  build:
    parameters:
      device:
        type: string
    docker:
      - image: cimg/base:2022.12
    steps:
      - checkout
      # Wonder if we can cache some of this so the setup steps don't take so long
      # Maybe a build step that makes the image with all the tools
      - run: sudo apt-get update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget python3-setuptools python3-pip
      - run: pip3 install pyyaml
      - run: ./setup.py --setup
      - run: ./openwrt/scripts/gen_config.py << parameters.device >>
      - run: make download -j$(nproc) -f ./openwrt/Makefile
      - run: make -j$(nproc) -f ./openwrt/Makefile
      - run: mkdir ./<< parameters.device >>
      - run: ./bin/circleci_archivebuild.sh << parameters.device >>
      - store_artifacts:
          path: ./<< parameters.device >>