---
version: 2.1
workflows:
  build:
    jobs:
      - prepare_cimg:
          context: deployable-service
      - build:
          requires:
            - prepare_cimg
          matrix:
            parameters:
              device: ["motorola_q14", "motorola_mh7020", "motorola_r14"]
          context: deployable-service

jobs:
  prepare_cimg:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      # Build a docker image with all the openwrt prereqs for the next steps
      - run: sudo apt-get update && sudo apt-get install awscli -y && sudo apt-get clean
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      # This script uses AWS CLI v1 (installed above). We could use cimg/aws runner if we improved the ECR login in here.
      - run: ./bin/circleci_buildciimg.sh
  build:
    parameters:
      device:
        type: string
    docker:
      - image: 674914898519.dkr.ecr.us-east-1.amazonaws.com/violetatrium/wlan-ap:ci-rev-${CIRCLE_SHA1}
    resource_class: xlarge
    steps:
      - checkout
      - run: ./setup.py --setup
      - run: 
          name: "Build OpenWRT configuration"
          no_output_timeout: 120m
          command : | 
            cd openwrt
            ./scripts/gen_config.py << parameters.device >>
            make download -j$(nproc) -f ./Makefile
            make V=s -j$(nproc) -f ./Makefile
      - run: mkdir ./<< parameters.device >>
      - run: ./bin/circleci_archivebuild.sh << parameters.device >>
      - store_artifacts:
          path: ./<< parameters.device >>